### ISSUE TITLE
Indent struct properties with names of reserved words properly

### ISSUE THREAD

**Issue by cs-victor-nascimento** [elixir-lang/emacs-elixir#170]
Just stumbled upon this tricky one when using s %ExUnit.Test{} struct. When I try to access the 'case' property it thinks its the start of a case expression and indents the next line as if it were inside the case expression.

For example, try this (don't mind my noobines in Elixir \o/):

![screenshot from 2015-02-03 10 51 31](https://cloud.githubusercontent.com/assets/7049728/6020392/a49fbaa0-ab92-11e4-995a-bdeb3efc07ec.png)

This may be tricky to get right. =/

Anyway, thanks for this great mode :D

**Comment by mattdeboard** [comment]
Thanks for opening this issue. I've added a failing regression test to capture this indentation bug.

**Comment by mattdeboard** [comment]
There are a couple of separate issues here:

1. Syntax highlighting. We can definitely hard-code a `(symbol-start (and (not (any ".")) builtin))` regex, but I don't think that is the right solution. What we want is to eliminate this entire class of syntax highlighting problem. My first thought is that updating the [elixir-rx macro](https://github.com/elixir-lang/emacs-elixir/blob/master/elixir-mode.el#L248-L255) to handle this might be a graceful place to start. Either that, or having a separate wrapping function that does this for *every* keyword.

2. Indentation. SMIE is looking at the grammar specification for [case..do..end](https://github.com/elixir-lang/emacs-elixir/blob/master/elixir-smie.el#L121) and performing the default indentation. Again, we can hard-code a fix for `.case` so that the next line is indented at the right level, but the right solution is to eliminate this problem entirely. A SMIE rule that looks backward for a preceding "." then adjusts the indentation appropriately is probably the right thing.

**Comment by mattdeboard** [comment]
We might want to think about updating the grammar to understand dotted notation...

**Comment by cs-victor-nascimento** [comment]
:+1: 

Do you think its best to open 2 issues or leave it as it is? 

Also, sorry I can't help much with the elisp side of things. Started reading the elisp manual but couldn't find time to practice it.

**Comment by mattdeboard** [comment]
No worries @cs-victor-nascimento just making notes for whoever reads the issue.

**Comment by mattdeboard** [comment]
And no one issue is fine.

**Comment by cs-victor-nascimento** [comment]
This seems to be fixed now :+1: 

You can close this one!
