### ISSUE TITLE
Indent multiclause function HEAD definition

### ISSUE THREAD

**Issue by cs-victor-nascimento** [elixir-lang/emacs-elixir#237]
When you are writing long function heads that you would like it to wrap to the next line it goes all the way back.

For example:

![screenshot from 2015-08-16 22 48 50](https://cloud.githubusercontent.com/assets/7049728/9296699/06ed99ba-4469-11e5-9f7c-393c741eb1b5.png)

In this case I think `when` should be idented one level. Though I've seen in Plug's code that they usually ident it until after `def `. A little example [here](https://github.com/elixir-lang/plug/blob/master/lib/plug/conn.ex#L584).

Thanks for the awesome mode!

**Comment by lexmag** [comment]
I think current indentation is correct, IMO.
In Elixir itself there are two styles can be seen:
* same indentation level as for `def`
* 2 extra levels (4 spaces) from `def`

**Comment by tonini** [comment]
I'll close this issue because like @lexmag I think it's the indentation as it works at the moment is not wrong. 

Thanks

**Comment by utkarshkukreti** [comment]
@tonini @lexmag 4 space indent seems to be used much more often than 0 space in Elixir Repo:

```
➜  elixir git:(master) ag '^  when.*do$' -s --elixir | wc -l
       7
➜  elixir git:(master) ag '^      when.*do$' -s --elixir | wc -l
      53
```

and 0 space is not used at all in Phoenix and Ecto:

```
➜  phoenix git:(master) ag '^  when.*do$' -s --elixir | wc -l
       0
➜  phoenix git:(master) ag '^      when.*do$' -s --elixir | wc -l
      16
➜  ecto git:(master) ag '^  when.*do$' -s --elixir | wc -l
       0
➜  ecto git:(master) ag '^      when.*do$' -s --elixir | wc -l
      22
```

(I know this regex is not 100% accurate and this does not include cases where the when condition is split over multiple lines.)

I think elixir-mode should default to 4 spaces.

**Comment by gausby** [comment]
I think that it is important to remember that just because Elixir core seems to favour a specific style it is by no means a hint of the current best practice followed by the Elixir core group; if such a best practice has been agreed upon at all.

Also, the results lack time. Could it be that the results that shows A was made in old commits and the B option is more prominent in later commits?

Personally I have no strong feelings towards the one or the other.

**Comment by utkarshkukreti** [comment]
In the additions from 1.0 to HEAD to .ex files:

```
➜  elixir git:(master) g diff v1.0.0..HEAD '*.ex' | ag '^\+  when.*do$' | wc -l
       7
➜  elixir git:(master) g diff v1.0.0..HEAD '*.ex' | ag '^\+      when.*do$' | wc -l
      40
```

And from 1.2.0 to HEAD:

```
➜  elixir git:(master) g diff v1.2.0..HEAD '*.ex' | ag '^\+  when.*do$' | wc -l
       2
➜  elixir git:(master) g diff v1.2.0..HEAD '*.ex' | ag '^\+      when.*do$' | wc -l
       9
```

**Comment by whatyouhide** [comment]
I slightly lean towards indenting the `when` with 4 spaces. My reasoning is that it aids readability (**for me** of course) because it separates the guard clauses from the body of the function in a more clear way; also, not indenting the *when* makes the function more cumbersome in my opinion, the code becomes a dense block and it's hard for me to separate the function head from the body. There are downsides to indenting as well of course: first, if there are many guards and those are aligned at the same level as the `when` or more then "rectangles" of whitespace will form (not very nice); second, as @lexmag pointed out in a private discussion, the `when` is really part of the function head so it may make sense to indent it on the same level.

Ultimately, the problem here IMO is that whatever style elixir-mode will choose, it will likely steer (part of) the community towards it (as there are many Emacs users in Elixir-land) so we should choose carefully; at the same time, there's no right indentation in this case, it's just a stylistic choice :)

**Comment by beta-phenylethylamine** [comment]
Is it possible to reopen this issue, seeing as it conflicts with how elixir-format formats the code?
