### ISSUE TITLE
Emacs 24.3.1. error

### ISSUE THREAD

**Issue by zw963** [elixir-lang/emacs-elixir#278]
```el
Debugger entered--Lisp error: (file-error "Cannot open load file" "pkg-info")
  require(pkg-info)
  eval-buffer(#<buffer  *load*> nil "/home/zw963/Dropbox/common/.emacs.d/plugins/elixir-mode/elixir-mode.el" nil t)  ; Reading at buffer position 1488
  load-with-code-conversion("/home/zw963/Dropbox/common/.emacs.d/plugins/elixir-mode/elixir-mode.el" "/home/zw963/Dropbox/common/.emacs.d/plugins/elixir-mode/elixir-mode.el" nil t)
  require(elixir-mode)
  eval((require (quote elixir-mode)) nil)
  eval-expression((require (quote elixir-mode)) nil)
  call-interactively(eval-expression nil nil)
```

But I not found `pkg-info.el` in this repository.

**Comment by zw963** [comment]
I have to download `pkg-info.e`l and `epl.el` to make this mode work, but not mention in README.

**Comment by syohex** [comment]
Dependencies are installed by installing with package.el or el-get.

**Comment by zw963** [comment]
I think should exist dependency document for those whose download package from github. thanks.

**Comment by tonini** [comment]
Hi,

I think @syohex is right. If you not using `package.el` at all and work with the source directory directly you're more or less an experienced Emacs user who knows how to check the dependency line on the header package file. [Header](https://github.com/elixir-lang/emacs-elixir/blob/master/elixir-mode.el#L14)

I think we don't need to mention these package dependencies on the README because of the reason explained above.

**Comment by tonini** [comment]
I'll close this issue for now.

Thanks for report and sharing your opinions. :+1:
