### ISSUE TITLE
Strange hang after RET after do

### ISSUE THREAD

**Issue by aaronjensen** [elixir-lang/emacs-elixir#363]
If you type a `do`, then press return, you get a weird hang. You can see a mark at the beginning of the line for a second or two. If you type, it inserts text, so it is not really hung, but it is visually jarring.

It appears to repro with just `elixir-mode` on `emacs -Q`

![hang](https://cloud.githubusercontent.com/assets/8588/15800500/608e5d62-2a30-11e6-9d00-2e0eb0af7b82.gif)

**Comment by TheGreenHabi** [comment]
I have same issue. It hangs for half a second

**Comment by tonini** [comment]
Thanks @aaronjensen I'll have a look at this one.

**Comment by gausby** [comment]
I can't reproduce.

@aaronjensen do you use spacemacs? Could you try to disable `ruby-end`—which sadly is included in the Elixir "layer"—and see if that solves the problem?

**Comment by aaronjensen** [comment]
> do you use spacemacs?

Yes, but not when i'm running `emacs -Q`



> Could you try to disable ruby-end—which sadly is included in the Elixir "layer"—and see if that solves the problem?

I'm on `develop` which uses `smartparens` instead. Even with `smartparens` disabled, this repros, and as I said, it reproduces on `emacs -Q`. I'm also on emacs 25, maybe this is a 25 issue?

**Comment by TheGreenHabi** [comment]
@aaronjensen @gausby I use spacemacs latest dev + latest packages (Win 10, emacs-w64 24.5.1)
So it's not an emacs 25 issue.
Strange thing is I actually installed ruby-end to have `end` inserted automatically before I press return. Ofcourse in pair with elixir-lang functionality it creates double `end`. But what interesting is this way it does not hang.
```elixir
def test do
  
end
  
end
```

**Comment by gausby** [comment]
I managed to reproduce this on OS X, running a clean Emacs 25.0.94.1, build with cocoa and all the bells and whistles. @TheGreenHabi seemed to reproduce it on Windows so it is not an OS issue.

To reproduce:
  
(1) open Emacs with no config file, `emacs -Q` from the terminal. (2) Insert the following in the scratch buffer and `eval-buffer`:
```elisp
(add-to-list 'load-path "~/.emacs.d/.cask/25.0.94.1/elpa/pkg-info-20150517.443/")
(add-to-list 'load-path "~/.emacs.d/.cask/25.0.94.1/elpa/epl-20150517.433/")
(add-to-list 'load-path "~/Development/forks/emacs-elixir/")

(require 'elixir-mode)
```
You might have to change the paths for your system. (3) open an Elixir file and type `def foo do<ret>`.

Some observations: The hang seems to happen for most block definitions, such as `def`, `defp`, `case`, `with`, etc, but not for `defmodule`. When defining a module it will echo `Mismatched parenthesis` to the minibuffer.

**Comment by gausby** [comment]
@TheGreenHabi I would recommend that you find an alternative way to auto insert `end`. `ruby-end` might work fine for Ruby, but the rules for do-blocks are different from Elixir, so you will end up correcting what it is doing most of the time. Personally I use some yasnippets where I have a “do”-snippet that expand do-end blocks.

**Comment by TheGreenHabi** [comment]
@gausby Thank you for advice! I will try `yasnippets` instead of `ruby-end`

**Comment by tonini** [comment]
Hi all,

Thanks for all the issue report and all the feedback.

I found the issue here https://github.com/elixir-lang/emacs-elixir/blob/master/elixir-smie.el#L315 in the call of `looking-back` and now try to figure it out why it hangs in this explained cases with `def...`. 

I'll let you know if I have more to say about it, thanks for your patience guys.

**Comment by gausby** [comment]
The delay goes away if `show-paren-mode` has been enabled in Elixir buffers.
```elisp
(show-paren-mode t)
```

**Comment by tonini** [comment]
I found the issue why it happens. Its about the rules defined for def, defp
etc. When removed the delay is gone. And yes all tests passing too so these
rules could be removed and actually are doesnt needed because the rule for
do...end is important.

Martin Gausby <notifications@github.com> schrieb am Mo., 6. Juni 2016,
13:04:

**Comment by gausby** [comment]
@tonini So, the same functionality with less code? Sounds like a bargain :)

**Comment by dgutov** [comment]
With those rules reverted, `show-paren-mode` doesn't work for `def`, `defp`, etc. It highlights their `do` and `end` in red.

**Comment by dgutov** [comment]
The problem is not fixed anyway: it still "hangs" after the "do"s for which SMIE rules remain. E.g. if I type `if expire do` and RET, it happens.

It happens because of a feature called `blink-matching-paren` (you can set this variable to nil, and the problem goes away; turning on `show-paren-mode` also helps because it disables it). There's still a bug in there somewhere, but it needs to be fixed differently.
